Issue: shortening URL containing a query param with no value causes Exception
ArgumentError: invalid data of application/x-www-form-urlencoded (searchNpi=1629006051&city=&firstName=&orgName=&searchType=ind&state=&npi=1629006051&orgDba=&lastName=&zip)
./lib/truncator/extended_uri.rb:48:in `query_parameters'
./lib/truncator/url_parser.rb:20:in `shorten_url'
./spec/url_parser_spec.rb:171:in `block (4 levels) in <top (required)>'